// Generated by gencpp from file turtle_bot/AbortResponse.msg
// DO NOT EDIT!


#ifndef TURTLE_BOT_MESSAGE_ABORTRESPONSE_H
#define TURTLE_BOT_MESSAGE_ABORTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Empty.h>

namespace turtle_bot
{
template <class ContainerAllocator>
struct AbortResponse_
{
  typedef AbortResponse_<ContainerAllocator> Type;

  AbortResponse_()
    : resp()  {
    }
  AbortResponse_(const ContainerAllocator& _alloc)
    : resp(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Empty_<ContainerAllocator>  _resp_type;
  _resp_type resp;




  typedef boost::shared_ptr< ::turtle_bot::AbortResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_bot::AbortResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AbortResponse_

typedef ::turtle_bot::AbortResponse_<std::allocator<void> > AbortResponse;

typedef boost::shared_ptr< ::turtle_bot::AbortResponse > AbortResponsePtr;
typedef boost::shared_ptr< ::turtle_bot::AbortResponse const> AbortResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_bot::AbortResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_bot::AbortResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_bot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'turtle_bot': ['/home/damien/SIR/ros-ws/src/turtle_bot/msg', '/home/damien/SIR/ros-ws/src/turtle_bot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::AbortResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::AbortResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::AbortResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::AbortResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::AbortResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::AbortResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_bot::AbortResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f2b402bcb064339495caf4c14031ad6";
  }

  static const char* value(const ::turtle_bot::AbortResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f2b402bcb064339ULL;
  static const uint64_t static_value2 = 0x495caf4c14031ad6ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_bot::AbortResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_bot/AbortResponse";
  }

  static const char* value(const ::turtle_bot::AbortResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_bot::AbortResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Empty resp\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Empty\n\
";
  }

  static const char* value(const ::turtle_bot::AbortResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_bot::AbortResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AbortResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_bot::AbortResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_bot::AbortResponse_<ContainerAllocator>& v)
  {
    s << indent << "resp: ";
    s << std::endl;
    Printer< ::std_msgs::Empty_<ContainerAllocator> >::stream(s, indent + "  ", v.resp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_BOT_MESSAGE_ABORTRESPONSE_H
