// Generated by gencpp from file turtle_bot/Abort.msg
// DO NOT EDIT!


#ifndef TURTLE_BOT_MESSAGE_ABORT_H
#define TURTLE_BOT_MESSAGE_ABORT_H

#include <ros/service_traits.h>


#include <turtle_bot/AbortRequest.h>
#include <turtle_bot/AbortResponse.h>


namespace turtle_bot
{

struct Abort
{

typedef AbortRequest Request;
typedef AbortResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Abort
} // namespace turtle_bot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_bot::Abort > {
  static const char* value()
  {
    return "ee74d6e9b57dcb99004ef8e8015741c5";
  }

  static const char* value(const ::turtle_bot::Abort&) { return value(); }
};

template<>
struct DataType< ::turtle_bot::Abort > {
  static const char* value()
  {
    return "turtle_bot/Abort";
  }

  static const char* value(const ::turtle_bot::Abort&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_bot::AbortRequest> should match 
// service_traits::MD5Sum< ::turtle_bot::Abort > 
template<>
struct MD5Sum< ::turtle_bot::AbortRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_bot::Abort >::value();
  }
  static const char* value(const ::turtle_bot::AbortRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_bot::AbortRequest> should match 
// service_traits::DataType< ::turtle_bot::Abort > 
template<>
struct DataType< ::turtle_bot::AbortRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_bot::Abort >::value();
  }
  static const char* value(const ::turtle_bot::AbortRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_bot::AbortResponse> should match 
// service_traits::MD5Sum< ::turtle_bot::Abort > 
template<>
struct MD5Sum< ::turtle_bot::AbortResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_bot::Abort >::value();
  }
  static const char* value(const ::turtle_bot::AbortResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_bot::AbortResponse> should match 
// service_traits::DataType< ::turtle_bot::Abort > 
template<>
struct DataType< ::turtle_bot::AbortResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_bot::Abort >::value();
  }
  static const char* value(const ::turtle_bot::AbortResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_BOT_MESSAGE_ABORT_H
