// Generated by gencpp from file turtle_bot/Entity.msg
// DO NOT EDIT!


#ifndef TURTLE_BOT_MESSAGE_ENTITY_H
#define TURTLE_BOT_MESSAGE_ENTITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <turtle_bot/ArenaPosition.h>

namespace turtle_bot
{
template <class ContainerAllocator>
struct Entity_
{
  typedef Entity_<ContainerAllocator> Type;

  Entity_()
    : label(0)
    , pose()  {
    }
  Entity_(const ContainerAllocator& _alloc)
    : label(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _label_type;
  _label_type label;

   typedef  ::turtle_bot::ArenaPosition_<ContainerAllocator>  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::turtle_bot::Entity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_bot::Entity_<ContainerAllocator> const> ConstPtr;

}; // struct Entity_

typedef ::turtle_bot::Entity_<std::allocator<void> > Entity;

typedef boost::shared_ptr< ::turtle_bot::Entity > EntityPtr;
typedef boost::shared_ptr< ::turtle_bot::Entity const> EntityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_bot::Entity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_bot::Entity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_bot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'turtle_bot': ['/home/damien/SIR/ros-ws/src/turtle_bot/msg', '/home/damien/SIR/ros-ws/src/turtle_bot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::Entity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::Entity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::Entity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::Entity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::Entity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::Entity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_bot::Entity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5179d64c5df761205b0c7adb36fa91b0";
  }

  static const char* value(const ::turtle_bot::Entity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5179d64c5df76120ULL;
  static const uint64_t static_value2 = 0x5b0c7adb36fa91b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_bot::Entity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_bot/Entity";
  }

  static const char* value(const ::turtle_bot::Entity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_bot::Entity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 label\n\
ArenaPosition pose\n\
================================================================================\n\
MSG: turtle_bot/ArenaPosition\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::turtle_bot::Entity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_bot::Entity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Entity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_bot::Entity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_bot::Entity_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.label);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::turtle_bot::ArenaPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_BOT_MESSAGE_ENTITY_H
