// Generated by gencpp from file turtle_bot/Entities.msg
// DO NOT EDIT!


#ifndef TURTLE_BOT_MESSAGE_ENTITIES_H
#define TURTLE_BOT_MESSAGE_ENTITIES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <turtle_bot/Entity.h>

namespace turtle_bot
{
template <class ContainerAllocator>
struct Entities_
{
  typedef Entities_<ContainerAllocator> Type;

  Entities_()
    : ent()  {
    }
  Entities_(const ContainerAllocator& _alloc)
    : ent(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::turtle_bot::Entity_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::turtle_bot::Entity_<ContainerAllocator> >::other >  _ent_type;
  _ent_type ent;




  typedef boost::shared_ptr< ::turtle_bot::Entities_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_bot::Entities_<ContainerAllocator> const> ConstPtr;

}; // struct Entities_

typedef ::turtle_bot::Entities_<std::allocator<void> > Entities;

typedef boost::shared_ptr< ::turtle_bot::Entities > EntitiesPtr;
typedef boost::shared_ptr< ::turtle_bot::Entities const> EntitiesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_bot::Entities_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_bot::Entities_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_bot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'turtle_bot': ['/home/damien/SIR/ros-ws/src/turtle_bot/msg', '/home/damien/SIR/ros-ws/src/turtle_bot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::Entities_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::Entities_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::Entities_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::Entities_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::Entities_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::Entities_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_bot::Entities_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59cc75e3d58b35a8ddd076389f747687";
  }

  static const char* value(const ::turtle_bot::Entities_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59cc75e3d58b35a8ULL;
  static const uint64_t static_value2 = 0xddd076389f747687ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_bot::Entities_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_bot/Entities";
  }

  static const char* value(const ::turtle_bot::Entities_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_bot::Entities_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Entity[] ent\n\
================================================================================\n\
MSG: turtle_bot/Entity\n\
uint16 label\n\
ArenaPosition pose\n\
================================================================================\n\
MSG: turtle_bot/ArenaPosition\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::turtle_bot::Entities_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_bot::Entities_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Entities_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_bot::Entities_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_bot::Entities_<ContainerAllocator>& v)
  {
    s << indent << "ent[]" << std::endl;
    for (size_t i = 0; i < v.ent.size(); ++i)
    {
      s << indent << "  ent[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::turtle_bot::Entity_<ContainerAllocator> >::stream(s, indent + "    ", v.ent[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_BOT_MESSAGE_ENTITIES_H
