// Generated by gencpp from file turtle_bot/Go.msg
// DO NOT EDIT!


#ifndef TURTLE_BOT_MESSAGE_GO_H
#define TURTLE_BOT_MESSAGE_GO_H

#include <ros/service_traits.h>


#include <turtle_bot/GoRequest.h>
#include <turtle_bot/GoResponse.h>


namespace turtle_bot
{

struct Go
{

typedef GoRequest Request;
typedef GoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Go
} // namespace turtle_bot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_bot::Go > {
  static const char* value()
  {
    return "ee74d6e9b57dcb99004ef8e8015741c5";
  }

  static const char* value(const ::turtle_bot::Go&) { return value(); }
};

template<>
struct DataType< ::turtle_bot::Go > {
  static const char* value()
  {
    return "turtle_bot/Go";
  }

  static const char* value(const ::turtle_bot::Go&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_bot::GoRequest> should match 
// service_traits::MD5Sum< ::turtle_bot::Go > 
template<>
struct MD5Sum< ::turtle_bot::GoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_bot::Go >::value();
  }
  static const char* value(const ::turtle_bot::GoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_bot::GoRequest> should match 
// service_traits::DataType< ::turtle_bot::Go > 
template<>
struct DataType< ::turtle_bot::GoRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_bot::Go >::value();
  }
  static const char* value(const ::turtle_bot::GoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_bot::GoResponse> should match 
// service_traits::MD5Sum< ::turtle_bot::Go > 
template<>
struct MD5Sum< ::turtle_bot::GoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_bot::Go >::value();
  }
  static const char* value(const ::turtle_bot::GoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_bot::GoResponse> should match 
// service_traits::DataType< ::turtle_bot::Go > 
template<>
struct DataType< ::turtle_bot::GoResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_bot::Go >::value();
  }
  static const char* value(const ::turtle_bot::GoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_BOT_MESSAGE_GO_H
