// Generated by gencpp from file turtle_bot/PanTilt.msg
// DO NOT EDIT!


#ifndef TURTLE_BOT_MESSAGE_PANTILT_H
#define TURTLE_BOT_MESSAGE_PANTILT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_bot
{
template <class ContainerAllocator>
struct PanTilt_
{
  typedef PanTilt_<ContainerAllocator> Type;

  PanTilt_()
    : pan(0.0)
    , tilt(0.0)  {
    }
  PanTilt_(const ContainerAllocator& _alloc)
    : pan(0.0)
    , tilt(0.0)  {
  (void)_alloc;
    }



   typedef double _pan_type;
  _pan_type pan;

   typedef double _tilt_type;
  _tilt_type tilt;




  typedef boost::shared_ptr< ::turtle_bot::PanTilt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_bot::PanTilt_<ContainerAllocator> const> ConstPtr;

}; // struct PanTilt_

typedef ::turtle_bot::PanTilt_<std::allocator<void> > PanTilt;

typedef boost::shared_ptr< ::turtle_bot::PanTilt > PanTiltPtr;
typedef boost::shared_ptr< ::turtle_bot::PanTilt const> PanTiltConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_bot::PanTilt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_bot::PanTilt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_bot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'turtle_bot': ['/home/damien/SIR/ros-ws/src/turtle_bot/msg', '/home/damien/SIR/ros-ws/src/turtle_bot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::PanTilt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::PanTilt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::PanTilt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::PanTilt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::PanTilt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::PanTilt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_bot::PanTilt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da61f3d6b381bd4af7a066f22fdfa441";
  }

  static const char* value(const ::turtle_bot::PanTilt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda61f3d6b381bd4aULL;
  static const uint64_t static_value2 = 0xf7a066f22fdfa441ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_bot::PanTilt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_bot/PanTilt";
  }

  static const char* value(const ::turtle_bot::PanTilt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_bot::PanTilt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pan\n\
float64 tilt\n\
";
  }

  static const char* value(const ::turtle_bot::PanTilt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_bot::PanTilt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan);
      stream.next(m.tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PanTilt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_bot::PanTilt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_bot::PanTilt_<ContainerAllocator>& v)
  {
    s << indent << "pan: ";
    Printer<double>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<double>::stream(s, indent + "  ", v.tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_BOT_MESSAGE_PANTILT_H
