// Generated by gencpp from file turtle_bot/PanTilts.msg
// DO NOT EDIT!


#ifndef TURTLE_BOT_MESSAGE_PANTILTS_H
#define TURTLE_BOT_MESSAGE_PANTILTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <turtle_bot/PanTilt.h>

namespace turtle_bot
{
template <class ContainerAllocator>
struct PanTilts_
{
  typedef PanTilts_<ContainerAllocator> Type;

  PanTilts_()
    : pts()  {
    }
  PanTilts_(const ContainerAllocator& _alloc)
    : pts(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::turtle_bot::PanTilt_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::turtle_bot::PanTilt_<ContainerAllocator> >::other >  _pts_type;
  _pts_type pts;




  typedef boost::shared_ptr< ::turtle_bot::PanTilts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_bot::PanTilts_<ContainerAllocator> const> ConstPtr;

}; // struct PanTilts_

typedef ::turtle_bot::PanTilts_<std::allocator<void> > PanTilts;

typedef boost::shared_ptr< ::turtle_bot::PanTilts > PanTiltsPtr;
typedef boost::shared_ptr< ::turtle_bot::PanTilts const> PanTiltsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_bot::PanTilts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_bot::PanTilts_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_bot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'turtle_bot': ['/home/damien/SIR/ros-ws/src/turtle_bot/msg', '/home/damien/SIR/ros-ws/src/turtle_bot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::PanTilts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::PanTilts_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::PanTilts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::PanTilts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::PanTilts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::PanTilts_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_bot::PanTilts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0e1ea58904b4e3619dccf3c18f43f66";
  }

  static const char* value(const ::turtle_bot::PanTilts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0e1ea58904b4e36ULL;
  static const uint64_t static_value2 = 0x19dccf3c18f43f66ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_bot::PanTilts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_bot/PanTilts";
  }

  static const char* value(const ::turtle_bot::PanTilts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_bot::PanTilts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PanTilt[] pts\n\
================================================================================\n\
MSG: turtle_bot/PanTilt\n\
float64 pan\n\
float64 tilt\n\
";
  }

  static const char* value(const ::turtle_bot::PanTilts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_bot::PanTilts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PanTilts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_bot::PanTilts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_bot::PanTilts_<ContainerAllocator>& v)
  {
    s << indent << "pts[]" << std::endl;
    for (size_t i = 0; i < v.pts.size(); ++i)
    {
      s << indent << "  pts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::turtle_bot::PanTilt_<ContainerAllocator> >::stream(s, indent + "    ", v.pts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_BOT_MESSAGE_PANTILTS_H
