// Generated by gencpp from file turtle_bot/Record.msg
// DO NOT EDIT!


#ifndef TURTLE_BOT_MESSAGE_RECORD_H
#define TURTLE_BOT_MESSAGE_RECORD_H

#include <ros/service_traits.h>


#include <turtle_bot/RecordRequest.h>
#include <turtle_bot/RecordResponse.h>


namespace turtle_bot
{

struct Record
{

typedef RecordRequest Request;
typedef RecordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Record
} // namespace turtle_bot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_bot::Record > {
  static const char* value()
  {
    return "ee74d6e9b57dcb99004ef8e8015741c5";
  }

  static const char* value(const ::turtle_bot::Record&) { return value(); }
};

template<>
struct DataType< ::turtle_bot::Record > {
  static const char* value()
  {
    return "turtle_bot/Record";
  }

  static const char* value(const ::turtle_bot::Record&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_bot::RecordRequest> should match 
// service_traits::MD5Sum< ::turtle_bot::Record > 
template<>
struct MD5Sum< ::turtle_bot::RecordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_bot::Record >::value();
  }
  static const char* value(const ::turtle_bot::RecordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_bot::RecordRequest> should match 
// service_traits::DataType< ::turtle_bot::Record > 
template<>
struct DataType< ::turtle_bot::RecordRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_bot::Record >::value();
  }
  static const char* value(const ::turtle_bot::RecordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_bot::RecordResponse> should match 
// service_traits::MD5Sum< ::turtle_bot::Record > 
template<>
struct MD5Sum< ::turtle_bot::RecordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_bot::Record >::value();
  }
  static const char* value(const ::turtle_bot::RecordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_bot::RecordResponse> should match 
// service_traits::DataType< ::turtle_bot::Record > 
template<>
struct DataType< ::turtle_bot::RecordResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_bot::Record >::value();
  }
  static const char* value(const ::turtle_bot::RecordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_BOT_MESSAGE_RECORD_H
