// Generated by gencpp from file turtle_bot/Service1Response.msg
// DO NOT EDIT!


#ifndef TURTLE_BOT_MESSAGE_SERVICE1RESPONSE_H
#define TURTLE_BOT_MESSAGE_SERVICE1RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace turtle_bot
{
template <class ContainerAllocator>
struct Service1Response_
{
  typedef Service1Response_<ContainerAllocator> Type;

  Service1Response_()
    : pose()  {
    }
  Service1Response_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::turtle_bot::Service1Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_bot::Service1Response_<ContainerAllocator> const> ConstPtr;

}; // struct Service1Response_

typedef ::turtle_bot::Service1Response_<std::allocator<void> > Service1Response;

typedef boost::shared_ptr< ::turtle_bot::Service1Response > Service1ResponsePtr;
typedef boost::shared_ptr< ::turtle_bot::Service1Response const> Service1ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_bot::Service1Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_bot::Service1Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_bot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'turtle_bot': ['/home/damien/SIR/ros-ws/src/turtle_bot/msg', '/home/damien/SIR/ros-ws/src/turtle_bot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::Service1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_bot::Service1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::Service1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_bot::Service1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::Service1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_bot::Service1Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_bot::Service1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "271cb12677c4cd9bccbc642cd9258d1f";
  }

  static const char* value(const ::turtle_bot::Service1Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x271cb12677c4cd9bULL;
  static const uint64_t static_value2 = 0xccbc642cd9258d1fULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_bot::Service1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_bot/Service1Response";
  }

  static const char* value(const ::turtle_bot::Service1Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_bot::Service1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D pose\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::turtle_bot::Service1Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_bot::Service1Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Service1Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_bot::Service1Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_bot::Service1Response_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_BOT_MESSAGE_SERVICE1RESPONSE_H
