(cl:defpackage turtle_bot-msg
  (:use )
  (:export
   "<ARENAPOSITION>"
   "ARENAPOSITION"
   "<ARENAPOSITION>"
   "ARENAPOSITION"
   "<ARENAPOSITIONS>"
   "ARENAPOSITIONS"
   "<ARENAPOSITIONS>"
   "ARENAPOSITIONS"
   "<AXIS>"
   "AXIS"
   "<AXIS>"
   "AXIS"
   "<ENTITIES>"
   "ENTITIES"
   "<ENTITIES>"
   "ENTITIES"
   "<ENTITY>"
   "ENTITY"
   "<ENTITY>"
   "ENTITY"
   "<PANTILT>"
   "PANTILT"
   "<PANTILT>"
   "PANTILT"
   "<PANTILTS>"
   "PANTILTS"
   "<PANTILTS>"
   "PANTILTS"
  ))

