# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtle_bot/Entity.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import turtle_bot.msg

class Entity(genpy.Message):
  _md5sum = "5179d64c5df761205b0c7adb36fa91b0"
  _type = "turtle_bot/Entity"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 label
ArenaPosition pose
================================================================================
MSG: turtle_bot/ArenaPosition
float64 x
float64 y"""
  __slots__ = ['label','pose']
  _slot_types = ['uint16','turtle_bot/ArenaPosition']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       label,pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Entity, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.label is None:
        self.label = 0
      if self.pose is None:
        self.pose = turtle_bot.msg.ArenaPosition()
    else:
      self.label = 0
      self.pose = turtle_bot.msg.ArenaPosition()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_H2d().pack(_x.label, _x.pose.x, _x.pose.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pose is None:
        self.pose = turtle_bot.msg.ArenaPosition()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.label, _x.pose.x, _x.pose.y,) = _get_struct_H2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_H2d().pack(_x.label, _x.pose.x, _x.pose.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pose is None:
        self.pose = turtle_bot.msg.ArenaPosition()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.label, _x.pose.x, _x.pose.y,) = _get_struct_H2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H2d = None
def _get_struct_H2d():
    global _struct_H2d
    if _struct_H2d is None:
        _struct_H2d = struct.Struct("<H2d")
    return _struct_H2d
